### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by lenbie** [Tartsi/tiralabra#1]
I downloaded the project on 17 February at 16:53.

# Running & Playing

- I was able to download and run the project without any problems
- It was fun to play against your AI, it seems that the AI makes good moves and is challenging to beat. Good job!
- It could be a nice addition to your game to let the player choose if they want to start, or if they want the AI to start
- Also, maybe add some more instructions to the beginning of the game: 
     -  First, maybe it's nice to mention that 5 in a row wins, just for completeness
     - Also, maybe clarify that you don't need to enter anything after Choice: and will be prompted to enter the row and column 
       later. This of course becomes clear when you try it out, but initially I was unsure if I needed to enter a tuple.
- I would also recommend adding row and column numbers at the sides of your board (like in chess). Since the command line game board is quite small, it's hard to count which row and column number I want to play

# Code
Overall, your code is clear and nice that you added explanatory docstring comments.

## General
- I saw you already noticed you still need to account for draw, so that's a good next step
- You could also add the option to immediately play again from the command line. This could involve creating functions to reset the board and other progress in the game, e.g. all moves made

## UI class
- I would recommend that instead of creating new instances of the Board, AI and Logic in the UI class constructor, you take them as arguments, so you would create the UI class like this UI(board, ai, logic). I think this is better practice, if I remember correctly from the ohjelmistotekniikka course material. You can then create the instances in index.py instead
- Also, maybe create separate variables or constants as inputs for the minimax (lines 77-78), so these are easily changeable, e.g. when you want to adjust the depth.

## Logic class
- You can remove the empty __init__ I think, Python should create it automatically

## AI class
- Your functions here seem very good, and I like that your evaluation considers also open ends, and not only number of own symbols in a row

# Tests
- All tests passed for me, very nice
- Maybe add tasks to run your tests and create coverage reports more easily (see ohjelmistotekniikka course materials), and/or add instructions for which commands to use into your README. Just to make it easier for the next reviewer.
- It seems you already noted this, but the next step here should be creating tests for your minimax. 

Overall, really good job!

**Comment by Tartsi** [comment]
Thank you very much for your insights. I will gladly start working on the issues you raised and they should be solved during this upcoming week.

**Comment by Tartsi** [comment]
19.02.2024

- Added Row, Column numbers to UI, now visible during play.
- Added more detailed instructions at the start of the game.
- Fixed redundant code in Logic.py, refactored UI-class code to index.py-file.

- TODO: Add draw, Add minimax testing, Add X and 0 both as playable pieces, Add restart directly from command line.

**Comment by Tartsi** [comment]
For the final release ended up adding draw + more minimax testing. 

Not in final release: Add X and 0 both as playable pieces, Add restart directly from command line.
