### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by AleksiSaxlund** [Tartsi/tiralabra#2]
Ladattu 23.02 klo. 15.40

Koko koodi kirjoitettu todella selvästi ja se on helppolukuista. Rakenne on myös luontevaa.

Algoritmi toimii hyvin ja nopeasti ainakin silloin, kun syvyytenä on 2. Koitin ja syvyys 3 tuntui toimivan myös hyvin, mutta syvyys 4 aiheutti jo huomattavaa hidastumista. 

Tekoäly ei osaa estää avokolmosta, mutta se johtuukin ainakin tällä hetkellä syvyydestä.

Testit vaikuttaa hyviltä sekä testikattavuus on korkea. 

Mahdollisena bugina?? saan seuraavan tulosteen kun pelaan itselleni voiton, jota tekoäly ei pysty estämään. Sen sijaan, että se antaisi pelaajan pelata peliä loppuun saakka.

Jos on tarkoituksellinen niin pelaajana on melko epätyydyttävää, että peliä ei pysty pelata loppuun saakka, koska tekoäly luovuttaa. 

```console
Row: 8
Column: 8
Moved to square (8 and 8)

    1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
 1  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 2  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 3  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 4  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 5  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 6  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 7  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 8  -  -  -  -  -  -  -  0  -  -  -  -  -  -  -  -  -  -  -  -
 9  -  -  -  -  -  -  -  0  0  0  -  -  -  -  -  -  -  -  -  -
10  -  -  -  -  -  -  -  0  -  X  -  -  -  -  -  -  -  -  -  -
11  -  -  -  -  -  -  -  0  X  X  X  X  0  -  -  -  -  -  -  -
12  -  -  -  -  -  -  -  -  -  X  X  0  -  -  -  -  -  -  -  -
13  -  -  -  -  -  -  -  -  -  X  X  -  -  -  -  -  -  -  -  -
14  -  -  -  -  -  -  -  -  -  0  -  X  -  -  -  -  -  -  -  -
15  -  -  -  -  -  -  -  -  -  -  -  -  0  -  -  -  -  -  -  -
16  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
17  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
18  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
19  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
20  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -

X has no moves left, 0 wins!
Game over! Thanks for playing.
```

Projekti on tosi hyvässä vaiheessa. Tsemppiä loppukurssille!

**Comment by Tartsi** [comment]
Kiitos vertaisarvioinnista.

Tekoälyn luovutus on tarkoituksella tehty ominaisuus, mutta nyt vertaisarvioinnin saaneena, ehkä se on järkevämpää laittaa palauttamaan vain paras mahdollinen siirto myös varman tappion edessä.

**Comment by Tartsi** [comment]
Lopulliseen palautukseen sain syvyydeksi 4, joka havaitsee kyseisen pelitilanteen issuessa. Tekoäly myös palauttaa peliä mahdollisimman paljon 'hidastavan' siirron varman tappion edetessä lopullisessa palautuksessa.

Kiitos vielä kerran palautteestanne!
